version: "3.8"

services:
    
    web:
        container_name: example-tom-morava-web
        build:
            context: .docker/web
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - .docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
    
    database:
        container_name: example-tom-morava-database
        build:
            context: .docker/database
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
            POSTGRES_DB: example
        volumes:
            - ./docker/database/data:/var/lib/postgresql/data
